/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as UserRouteImport } from './routes/user'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as UserIndexRouteImport } from './routes/user.index'
import { Route as UserProfileRouteImport } from './routes/user.profile'
import { Route as UserSecurityRouteImport } from './routes/user.security'
import { Route as UserWishlistRouteImport } from './routes/user.wishlist'
import { Route as PublicSlugIndexRouteImport } from './routes/_public/$slug/index'
import { Route as PublicBlogIndexRouteImport } from './routes/_public/blog/index'
import { Route as PublicCategorySlugRouteImport } from './routes/_public/category/$slug'
import { Route as PublicLoginIndexRouteImport } from './routes/_public/login/index'
import { Route as PublicSignupIndexRouteImport } from './routes/_public/signup/index'
import { Route as PublicStoreIndexRouteImport } from './routes/_public/store/index'
import { Route as PublicSubCategorySlugRouteImport } from './routes/_public/sub-category/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PublicBlogSlugIndexRouteImport } from './routes/_public/blog/$slug/index'
import { Route as PublicProductSlugIndexRouteImport } from './routes/_public/product/$slug/index'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserSecurityRoute = UserSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => UserRoute,
} as any)
const UserWishlistRoute = UserWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => UserRoute,
} as any)
const PublicSlugIndexRoute = PublicSlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCategorySlugRoute = PublicCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignupIndexRoute = PublicSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicStoreIndexRoute = PublicStoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSubCategorySlugRoute = PublicSubCategorySlugRouteImport.update({
  id: '/sub-category/$slug',
  path: '/sub-category/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicBlogSlugIndexRoute = PublicBlogSlugIndexRouteImport.update({
  id: '/blog/$slug/',
  path: '/blog/$slug/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProductSlugIndexRoute = PublicProductSlugIndexRouteImport.update({
  id: '/product/$slug/',
  path: '/product/$slug/',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/user': typeof UserRouteWithChildren
  '/user/profile': typeof UserProfileRoute
  '/user/security': typeof UserSecurityRoute
  '/user/wishlist': typeof UserWishlistRoute
  '/user/': typeof UserIndexRoute
  '/category/$slug': typeof PublicCategorySlugRoute
  '/sub-category/$slug': typeof PublicSubCategorySlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$slug/': typeof PublicSlugIndexRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/login/': typeof PublicLoginIndexRoute
  '/signup/': typeof PublicSignupIndexRoute
  '/store/': typeof PublicStoreIndexRoute
  '/blog/$slug/': typeof PublicBlogSlugIndexRoute
  '/product/$slug/': typeof PublicProductSlugIndexRoute
}
export interface FileRoutesByTo {
  '/user/profile': typeof UserProfileRoute
  '/user/security': typeof UserSecurityRoute
  '/user/wishlist': typeof UserWishlistRoute
  '/': typeof PublicIndexRoute
  '/user': typeof UserIndexRoute
  '/category/$slug': typeof PublicCategorySlugRoute
  '/sub-category/$slug': typeof PublicSubCategorySlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$slug': typeof PublicSlugIndexRoute
  '/blog': typeof PublicBlogIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/signup': typeof PublicSignupIndexRoute
  '/store': typeof PublicStoreIndexRoute
  '/blog/$slug': typeof PublicBlogSlugIndexRoute
  '/product/$slug': typeof PublicProductSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/user/profile': typeof UserProfileRoute
  '/user/security': typeof UserSecurityRoute
  '/user/wishlist': typeof UserWishlistRoute
  '/_public/': typeof PublicIndexRoute
  '/user/': typeof UserIndexRoute
  '/_public/category/$slug': typeof PublicCategorySlugRoute
  '/_public/sub-category/$slug': typeof PublicSubCategorySlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_public/$slug/': typeof PublicSlugIndexRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
  '/_public/signup/': typeof PublicSignupIndexRoute
  '/_public/store/': typeof PublicStoreIndexRoute
  '/_public/blog/$slug/': typeof PublicBlogSlugIndexRoute
  '/_public/product/$slug/': typeof PublicProductSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user'
    | '/user/profile'
    | '/user/security'
    | '/user/wishlist'
    | '/user/'
    | '/category/$slug'
    | '/sub-category/$slug'
    | '/api/auth/$'
    | '/$slug/'
    | '/blog/'
    | '/login/'
    | '/signup/'
    | '/store/'
    | '/blog/$slug/'
    | '/product/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/user/profile'
    | '/user/security'
    | '/user/wishlist'
    | '/'
    | '/user'
    | '/category/$slug'
    | '/sub-category/$slug'
    | '/api/auth/$'
    | '/$slug'
    | '/blog'
    | '/login'
    | '/signup'
    | '/store'
    | '/blog/$slug'
    | '/product/$slug'
  id:
    | '__root__'
    | '/_public'
    | '/user'
    | '/user/profile'
    | '/user/security'
    | '/user/wishlist'
    | '/_public/'
    | '/user/'
    | '/_public/category/$slug'
    | '/_public/sub-category/$slug'
    | '/api/auth/$'
    | '/_public/$slug/'
    | '/_public/blog/'
    | '/_public/login/'
    | '/_public/signup/'
    | '/_public/store/'
    | '/_public/blog/$slug/'
    | '/_public/product/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/security': {
      id: '/user/security'
      path: '/security'
      fullPath: '/user/security'
      preLoaderRoute: typeof UserSecurityRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/wishlist': {
      id: '/user/wishlist'
      path: '/wishlist'
      fullPath: '/user/wishlist'
      preLoaderRoute: typeof UserWishlistRouteImport
      parentRoute: typeof UserRoute
    }
    '/_public/$slug/': {
      id: '/_public/$slug/'
      path: '/$slug'
      fullPath: '/$slug/'
      preLoaderRoute: typeof PublicSlugIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/category/$slug': {
      id: '/_public/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof PublicCategorySlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signup/': {
      id: '/_public/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof PublicSignupIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/store/': {
      id: '/_public/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof PublicStoreIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sub-category/$slug': {
      id: '/_public/sub-category/$slug'
      path: '/sub-category/$slug'
      fullPath: '/sub-category/$slug'
      preLoaderRoute: typeof PublicSubCategorySlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/blog/$slug/': {
      id: '/_public/blog/$slug/'
      path: '/blog/$slug'
      fullPath: '/blog/$slug/'
      preLoaderRoute: typeof PublicBlogSlugIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/product/$slug/': {
      id: '/_public/product/$slug/'
      path: '/product/$slug'
      fullPath: '/product/$slug/'
      preLoaderRoute: typeof PublicProductSlugIndexRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCategorySlugRoute: typeof PublicCategorySlugRoute
  PublicSubCategorySlugRoute: typeof PublicSubCategorySlugRoute
  PublicSlugIndexRoute: typeof PublicSlugIndexRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
  PublicSignupIndexRoute: typeof PublicSignupIndexRoute
  PublicStoreIndexRoute: typeof PublicStoreIndexRoute
  PublicBlogSlugIndexRoute: typeof PublicBlogSlugIndexRoute
  PublicProductSlugIndexRoute: typeof PublicProductSlugIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicCategorySlugRoute: PublicCategorySlugRoute,
  PublicSubCategorySlugRoute: PublicSubCategorySlugRoute,
  PublicSlugIndexRoute: PublicSlugIndexRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
  PublicLoginIndexRoute: PublicLoginIndexRoute,
  PublicSignupIndexRoute: PublicSignupIndexRoute,
  PublicStoreIndexRoute: PublicStoreIndexRoute,
  PublicBlogSlugIndexRoute: PublicBlogSlugIndexRoute,
  PublicProductSlugIndexRoute: PublicProductSlugIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface UserRouteChildren {
  UserProfileRoute: typeof UserProfileRoute
  UserSecurityRoute: typeof UserSecurityRoute
  UserWishlistRoute: typeof UserWishlistRoute
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserProfileRoute: UserProfileRoute,
  UserSecurityRoute: UserSecurityRoute,
  UserWishlistRoute: UserWishlistRoute,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
